name: rerun-workflows-action
description: Rerun failed workflow runs

inputs:
  event:
    description: Event name of workflow runs
    required: false
  sha:
    description: Commit SHA of workflow runs
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  workflow-runs-count:
    description: Number of rerun workflow runs

runs:
  using: 'node20'
  main: 'dist/index.js'
