name: fixture

on:
  pull_request:
    # This must be same as ts.yaml
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  success-on-rerun:
    strategy:
      fail-fast: false
      matrix:
        id: [10, 20, 30]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: sleep '${{ matrix.id }}'
      - run: test ${{ github.run_attempt }} = 2
