name: rerun-by-label

on:
  pull_request:
    types:
      - labeled

jobs:
  rerun-workflows:
    if: github.event.label.name == '/rerun'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write # To rerun workflows
      pull-requests: write # To remove label
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build

      - name: Use int128/rerun-workflows-action
        uses: ./

      - uses: int128/label-action@56e6a6baf6dfbcdcab9e3cd7e45ba37a4522fe63 # v1.45.0
        with:
          remove-labels: ${{ github.event.label.name }}
