name: rerun-on-label

on:
  issue_comment:
    types:
      - created

jobs:
  rerun-workflows:
    if: github.event.comment.body == '/rerun'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write # rerun-workflows
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: get-head-sha
        with:
          result-encoding: string
          script: |
            const { data: pull } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            })
            return pull.head.sha
      - name: Use int128/rerun-workflows-action
        uses: ./
        with:
          event: ${{ github.event_name }}
          sha: ${{ steps.get-head-sha.outputs.result }}
