name: rerun-on-label

on:
  pull_request:
    types:
      - labeled

jobs:
  rerun-workflows:
    if: github.event.label.name == 'rerun'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write # rerun-workflows
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - name: Use int128/rerun-workflows-action
        uses: ./
        with:
          event: ${{ github.event_name }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Remove the label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              name: context.payload.label.name,
            })
